[package]
name = "schedule-updater"
version = "0.2.0"
authors = ["bryan tdeters <bryantdeters@gmail.com>"]
edition = "2021"

[dependencies]
reqwest = {version = "0.12.9", features = ["blocking"]}
regex = "1"